query getWine($id: String!) {
  getWine(id: $id) {
    _id
    name
    enName
    image
    category
    country
    grape
    price
    sweet
    body
    acidity
    tanin
    winery
    foodMatching
  }
}
