name: Github Action Test

on:
  workflow_dispatch:
    inputs:
      test:
        type: environment
        required: true
        description: "정기배포 여부를 선택해주세요."
        options:
          - myrealtrip
          - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
